CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roll_number VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    resolved_count INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    image_url VARCHAR(255) DEFAULT NULL,
    reporter_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    is_found BOOLEAN DEFAULT FALSE,
    report_id BIGINT UNIQUE NOT NULL,
    status VARCHAR(20) DEFAULT 'pending',
    user_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_items_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_items_item_type ON items (item_type);
CREATE INDEX IF NOT EXISTS idx_items_status ON items (status);
CREATE INDEX IF NOT EXISTS idx_items_is_found ON items (is_found);
CREATE INDEX IF NOT EXISTS idx_items_report_id ON items (report_id);
CREATE INDEX IF NOT EXISTS idx_items_user_id ON items (user_id);

CREATE TABLE IF NOT EXISTS match_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lost_item_id INTEGER NOT NULL,
    found_item_id INTEGER NOT NULL,
    matched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_by VARCHAR(50),

    CONSTRAINT fk_match_lost FOREIGN KEY (lost_item_id) REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT fk_match_found FOREIGN KEY (found_item_id) REFERENCES items(id) ON DELETE CASCADE
);